package com.cs.enums;

public enum ConfigProperties {

	URL,
	PASSEDSTEPSCREENSHOT,
	FAILEDSTEPSSCREENSHOT,
	RETRYFAILEDTESTS,
	SELENIUM_GRID_ENABLED,
	SELENIUM_GRID_HUBHOST,
	ELASTICSEARCH_HOST,
	BROWSER, ;
	
}
